name: Xcode build

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12_beta.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Xcode build iOS App
      run: |
        xcodebuild clean build -scheme netdata -destination 'platform=iOS Simulator,name=iPhone 11,OS=14'
